### ISSUE TITLE
no source

### ISSUE THREAD

**Issue by vikikee** [a-sync/rtlmost-downloader#10]
Szia, Ezt a hibat kapom.

Your environment has been set up for using Node.js 10.16.3 (x64) and npm.

C:\Windows\System32>rtlmost-downloader
? Oldal link: https://www.rtlmost.hu/love-island-p_14735/love-island-1-evad-24-resz-c_12509503
? Fájl név: love-island-1-evad-24-resz.mp4
√ Oldal betöltése...
× Nem található letölthető url.
? Videó URL (Use arrow keys)
> Love-Island_c12509503_Love-Island-1-evad-2_unpnp.ism

[http://bit.ly/2kUjU3X](RTL-Failed-Pic)

**Comment by a-sync** [comment]
Szia,
próbáld meg a youtube-dl programmal (https://github.com/ytdl-org/youtube-dl).
Az rtlmost-downloader fejlesztését abba hagytam.

**Comment by vikikee** [comment]
> Szia,
> próbáld meg a youtube-dl programmal (https://github.com/ytdl-org/youtube-dl).
> Az rtlmost-downloader fejlesztését abba hagytam.

Szia
Rendben megprobalom, koszi szepen :)
 edit:
Mar javaban daralom vele, nagyon koszi a tippet! :)
