### ISSUE TITLE
Letöltési hely beállítás

### ISSUE THREAD

**Issue by Toninho13** [a-sync/rtlmost-downloader#3]
Hello!
Raspberry pi-n használom raspbian alatt a programot. Hogyan tudnám beállítani a letöltési helyet? Ha outputtal írom a helyet, akkor is csak a home mappába hajlandó letölteni.
Előre is köszönöm a segítséget!

**Comment by a-sync** [comment]
Szia,
az input validálás csak fájl név megadását tette lehetővé, ezért mindig a futtatási könyvtárba került. (cwd)
Most frissítettem rajta és útvonal esetén is csak a fájlnév részét validálja.  Továbbá ha könyvtárat adsz meg, akkor hozzáfűzi a kitalált vagy generált fájlnevet.
Próbáld meg a legújabb verzióval kérlek.

**Comment by Toninho13** [comment]
Szia!
Nagyon szépem köszönöm! A program is nagyon jó, valamint most már mappát is tudok állítani! Köszi még egyszer!
