### ISSUE TITLE
A 2018.11.10 xfaktor-nál nem talál URL-t

### ISSUE THREAD

**Issue by denymen** [a-sync/rtlmost-downloader#6]
Video URL: https://www.rtlmost.hu/x-faktor-p_7680/x-faktor-2018-11-10-c_12206233
output:
? Oldal link: https://www.rtlmost.hu/x-faktor-p_7680/x-faktor-2018-11-10-c_12206233
? Fájl név: x-faktor-2018-11-10.mp4
√ Oldal betöltése...
× Nem található letölthető url.
? Videó URL X-Faktor_c12206233_X-Faktor-2018-11-10_sd3.m3u8
× Videó letöltése sikertelen!

**Comment by a-sync** [comment]
Az általad megadott url nekem nem nyílik meg. (404)
Ezzel viszont működik: https://www.rtlmost.hu/x-faktor-p_7680/x-faktor-2018-11-10-c_12207107
¯\\\_(ツ)\_/¯

**Comment by denymen** [comment]
Valamit akkor csinálhattak vele azóta, mert a hozzászólásomban írt URL-en kellett megnéznünk sajna. Viszont furcsa is volt, hogy flash player kellett neki, ellentétben a többi résszel. Na mindegy, lényeg hogy már megoldódott. Köszi a gyors választ!
