### ISSUE TITLE
Videó URL kinyerése sikertelen!

### ISSUE THREAD

**Issue by szivalaszlo** [a-sync/rtlmost-downloader#8]
Minden linkre ezt a hibát dobja. Lehet köze ahhoz, hogy betettek egy reklámot közvetlenül a videó elé?

**Comment by a-sync** [comment]
Hmm.. elképzelhető. Hétvége felé ránézek mi lehet a gond.

**Comment by szivalaszlo** [comment]
Köszi! Kedvelem a kódot, és sokat használtam eddig. Írtam hozzá egy pici Java progit, ami kezelni tud egy listányi linket, és letölti mindet. :D
