### ISSUE TITLE
Sorozat letöltése egyben

### ISSUE THREAD

**Issue by djrooli** [a-sync/rtlmost-downloader#9]
Először is köszi a progit!

Márodszor, egy olyan kérdésem lenne, hogy ha mondjuk a
ShowderKlubbot tölteném le, az bazi sok videó egyenként.
Ezt valahogy egyben le tudnám húzni?

Harmadszor pedig Aranyeső Yuccában c. filmet nem találja az IDM (internet download manager), viszont a minden mást eddig leszedett. Lehúztam ezzel is és az IDM-mel is, összehasonlítottam a Nevem Senki két letöltött változatát, a kép ugyanaz, a hangot viszont rosszabbul tömöríti. IDM : 104 kbps aac | RTL DL : 93 kbps aac. Hallható különbség nincs,
nem néztem még utána az aac kódoláshoz, nem használom, spek nem mutatott különbséget, így igazából ezzel nincs is gond.

Előre is köszi a választ.

**Comment by a-sync** [comment]
Szia, ehhez valamivel külön ki kellene gyűjteni az összes linket, és végigmenni rajtuk, ezt nem támogatja a progi, nem is cél őszintén szólva. Torrent oldalakról le tudod tölteni az évadokat egyben, inkább azt javasolnám, vagy valami segédprogramot kell írni ami a kigyűjtést elvégzi és linkekkel meghívja ezt a programot.

A hang kérdést passzolom, ffmpeg audio codec beállítása *copy*-n van tehát a streamelt tartalommal megegyezőnek kellene lennie.

Továbbá javaslom, hogy próbáld meg a youtube-dl programmal is, háthat jobb eredményt kapsz. Kb. 1 hónapja támogatja az rtlmost-os linkeket (sok más oldal mellett) és a továbbiakban oda mennek majd a frissítések is. Ennek a proginak a támogatása a másik mellett felesleges, és a részemről megszűnik.

**Comment by djrooli** [comment]
köszönöm a választ!
